name: dart_sandbox
description: Sandbox environment for running Dart programs.
version: 1.0.0
repository: https://github.com/localtoast3000/dart_sandbox

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
